source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'

target 'Aiper-IFA-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Comment the next line if you don't want to use dynamic frameworks
  #UI
  pod 'SnapKit', '5.7.1' #约束
  pod 'MJRefresh', '3.7.9' # 刷新
  pod 'SwiftyAttributes', '5.4.0'
  pod 'YModemLib', '1.0.2' #, '~> 1.0.2' 有bug，不适合WR

  pod 'Jelly', '2.3.0' # 动画
  pod 'EmptyDataSet-Swift', '5.0.0' # https://github.com/Xiaoye220/EmptyDataSet-Swift
  pod 'GKNavigationBarSwift', '1.7.3'# 导航的
  pod 'Kingfisher', '8.9.0'#图片加载
  pod 'lottie-ios', '4.6.0'
  pod 'SVGAPlayer', :git => 'https://github.com/ad-Jun/SVGAPlayer-iOS', :commit => '8b02e1c20d8692e29cfb86e0303feb0f7b91d6d7'
  pod 'Protobuf', '3.29.6'
  pod 'SSZipArchive', '2.4.3'
  
  #pod 'SVGAPlayer'#SVGA加载 https://github.com/svga/SVGAPlayer-iOS
  pod 'SVGKit', '3.0.0' #SVG加载 https://github.com/SVGKit/SVGKit //弃用

  pod 'SVProgressHUD', '2.3.1'
  #pod 'Toaster' # 这玩意有bug；横屏用不了，竖屏可以
  pod 'Toast-Swift', '5.1.1' # https://github.com/scalessec/Toast-Swift
  pod 'SwiftDate', '7.0.0' #

  #  #SYSTEM
  #pod 'DeviceKit'
  pod 'IQKeyboardManagerSwift', '6.5.16'
  pod 'DefaultsKit', '0.3.2' # https://github.com/nmdias/DefaultsKit

  #  #NETWORK
  pod 'Moya/RxSwift', '15.0.0'
  # 亚马逊
  pod 'AWSMobileClient', '2.41.0'
  pod 'AWSIoT', '2.41.0'
  #pod 'AWSCognito'
  pod 'CryptoSwift', '1.8.4' # https://github.com/krzyzanowskim/CryptoSwift
  pod 'SwiftyRSA', '1.7.0' #https://github.com/TakeScoop/SwiftyRSA
  pod 'DGCharts', :git => 'https://github.com/ad-Jun/Charts', :commit => '4d4955ef251a8b309b04b712ccf2792ce4cbd379'
  pod 'DZNEmptyDataSet', '1.8.1' #https://github.com/dzenbot/DZNEmptyDataSet

  #  #DATA
  #pod 'SwifterSwift'
  pod 'CleanJSON', '1.0.9'
  pod 'R.swift', '7.8.0' # https://github.com/mac-cain13/R.swift
  pod 'SwiftProtobuf', '1.38.0' #https://github.com/apple/swift-protobuf.git
  pod 'YYCache', '1.0.4'

  # RX
  pod 'RxCocoa', '6.9.0'
  pod 'RxSwift', '6.9.0'

  pod 'NSObject+Rx', '5.2.2' # https://github.com/RxSwiftCommunity/NSObject-Rx
  pod 'RxURLNavigator', '3.0.0'
  pod 'RxDataSources', '5.0.0' # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'RxActivityIndicator', '2.0.0' # https://github.com/InsectQY/RxActivityIndicator
  pod 'RxReachability', '1.2.1' # https://github.com/RxSwiftCommunity/RxReachability
  pod 'RxOptional', '5.0.6' # https://github.com/RxSwiftCommunity/RxOptional
  pod 'RxViewController', '2.0.0'  # https://github.com/devxoul/RxViewController

  # 国际化
  pod 'Localize-Swift', '3.2.0' #本地化 # https://github.com/marmelroy/Localize-Swift

  # Test
  pod 'LookinServer', '1.2.8', :configurations => ['Debug']
  pod 'CocoaDebug', '1.7.7', :configurations => ['Debug','Release']

  pod 'SwiftyBeaver', '2.1.1'


  pod 'SensorsAnalyticsSDK', '5.0.0' #开启 crash 功能，需要集成 Exception 和 Core 模块
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'SGQRCode', '4.1.0'
  pod 'FSCalendar', '2.8.4'
  pod 'JXPhotoBrowser', '4.0.3' #https://github.com/JiongXing/PhotoBrowser
  pod 'TZImagePickerController/Basic', '3.8.12' #https://github.com/banchichen/TZImagePickerController

  pod 'iOSDFULibrary', '4.15.3'
  pod 'MLeaksFinder', :git => 'https://github.com/Tencent/MLeaksFinder.git', :commit => 'd598dd8644aa48ee63e40d88ecbd69598cc7adf1', :configurations => ['Debug']

  # feebook分享
  #pod 'FBSDKShareKit'
  # ins
  #pod 'FBSDKCoreKit'

  #智齿
  #pod 'SobotChatClient' #, '~> 4.1.4' #https://developer.zhichi.com/pages/97fddc/#_2-2-cocopods集成


end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      # 修复 YModemLib 缺少 stdint.h
      if target.name == "YModemLib"
        file_path = "Pods/YModemLib/YModemLib/YModem/YModem.h"
        if File.exist?(file_path)
          # 增加写权限
          File.chmod(0644, file_path)
          content = File.read(file_path)
          unless content.include?("#include <stdint.h>")
            new_content = "#include <stdint.h>\n" + content
            File.open(file_path, "w") do |file|
              file.write(new_content)
            end
          end
        end
      end
      # 全局 Build Settings
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
